// =========================================
// Seed Script - Populate with sample data
// Demonstrates the full schema and provides
// initial data for dashboard testing
// =========================================
require('dotenv').config();
const mongoose = require('mongoose');
const database = require('../config/database');
const AiTool = require('../models/AiTool');
const logger = require('../utils/logger');

const sampleTools = [
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    description: 'An AI-powered conversational agent built by OpenAI using GPT-4 and GPT-3.5 models. It can answer questions, write code, create content, analyze data, and assist with a wide range of tasks using natural language.',
    short_description: 'AI chatbot by OpenAI for conversation, coding, writing, and analysis.',
    website: 'https://chat.openai.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    category: 'AI Chatbots',
    sub_category: 'Virtual Assistant',
    tags: ['ai', 'chatbot', 'gpt', 'llm', 'openai', 'productivity', 'coding', 'writing'],
    pricing: { model: 'Freemium', starting_price: '$20/mo', currency: 'USD' },
    free_plan: true,
    features: ['Natural language conversation', 'Code generation and debugging', 'Content writing', 'Data analysis', 'Image understanding', 'Plugin ecosystem', 'Custom GPTs', 'File uploads'],
    github_stars: 0,
    producthunt_votes: 3500,
    hackernews_points: 2500,
    hackernews_mentions: 150,
    social_signals: { twitter_mentions: 50000, reddit_mentions: 25000, total_engagement: 75000 },
    search_interest: 95,
    trend_score: 95.5,
    trend_direction: 'stable',
    feature_innovation_score: 0.95,
    source: 'manual',
    release_date: new Date('2022-11-30'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'AI-powered image generation tool that creates stunning artwork and images from text prompts. Known for its artistic style and high-quality outputs.',
    short_description: 'AI image generator creating stunning artwork from text prompts.',
    website: 'https://midjourney.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png',
    category: 'AI Image Generation',
    sub_category: 'Image Generation',
    tags: ['ai', 'image generation', 'art', 'text-to-image', 'design', 'creative'],
    pricing: { model: 'Paid', starting_price: '$10/mo', currency: 'USD' },
    free_plan: false,
    features: ['Text-to-image generation', 'Style mixing', 'Image upscaling', 'Variation generation', 'Pan and zoom', 'Multi-prompt support'],
    github_stars: 0,
    producthunt_votes: 2800,
    hackernews_points: 1200,
    social_signals: { twitter_mentions: 40000, reddit_mentions: 20000, total_engagement: 60000 },
    search_interest: 85,
    trend_score: 88.2,
    trend_direction: 'stable',
    feature_innovation_score: 0.90,
    source: 'manual',
    release_date: new Date('2022-07-12'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor built on VS Code that uses advanced AI models for code generation, editing, and understanding. Features include AI-powered autocomplete, chat, and codebase-aware assistance.',
    short_description: 'AI-first code editor with intelligent code generation and chat.',
    website: 'https://cursor.sh',
    logo: '',
    category: 'AI Coding',
    sub_category: 'Code Generation',
    tags: ['ai', 'coding', 'ide', 'code generation', 'developer', 'productivity', 'vscode'],
    pricing: { model: 'Freemium', starting_price: '$20/mo', currency: 'USD' },
    free_plan: true,
    features: ['AI code completion', 'Codebase-aware chat', 'Multi-file editing', 'Error detection', 'Code refactoring', 'Terminal integration'],
    github_stars: 2500,
    producthunt_votes: 1800,
    hackernews_points: 800,
    social_signals: { twitter_mentions: 15000, reddit_mentions: 8000, total_engagement: 23000 },
    search_interest: 78,
    trend_score: 82.5,
    trend_direction: 'rising',
    feature_innovation_score: 0.88,
    source: 'manual',
    release_date: new Date('2023-03-01'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Stability AI',
    slug: 'stability-ai',
    description: 'Open-source AI company behind Stable Diffusion, offering image generation, video generation, and language models. Provides both consumer products and enterprise APIs.',
    short_description: 'Creators of Stable Diffusion - open-source AI image generation.',
    website: 'https://stability.ai',
    logo: '',
    category: 'AI Image Generation',
    sub_category: 'Image Generation',
    tags: ['ai', 'image generation', 'open source', 'stable diffusion', 'api', 'text-to-image'],
    pricing: { model: 'Freemium', starting_price: '$10/mo', currency: 'USD' },
    free_plan: true,
    features: ['Text-to-image generation', 'Image editing', 'Inpainting', 'Outpainting', 'API access', 'Open source models'],
    github_stars: 65000,
    github_forks: 9500,
    github_url: 'https://github.com/Stability-AI/stablediffusion',
    github_star_growth: 120,
    producthunt_votes: 2200,
    hackernews_points: 900,
    social_signals: { twitter_mentions: 30000, reddit_mentions: 15000, total_engagement: 45000 },
    search_interest: 72,
    trend_score: 79.8,
    trend_direction: 'stable',
    feature_innovation_score: 0.85,
    source: 'github',
    release_date: new Date('2022-08-22'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'LangChain',
    slug: 'langchain',
    description: 'Framework for developing applications powered by large language models. Provides abstractions for chains, agents, memory, and tool integrations.',
    short_description: 'Framework for building LLM-powered applications with chains and agents.',
    website: 'https://langchain.com',
    logo: '',
    category: 'AI Coding',
    sub_category: 'Code Generation',
    tags: ['ai', 'llm', 'framework', 'langchain', 'developer', 'open source', 'rag', 'agents'],
    pricing: { model: 'Open Source', currency: 'USD' },
    free_plan: true,
    features: ['LLM chains', 'AI agents', 'Memory management', 'RAG support', 'Tool integrations', 'Multi-model support', 'Streaming'],
    github_stars: 82000,
    github_forks: 12500,
    github_url: 'https://github.com/langchain-ai/langchain',
    github_star_growth: 200,
    producthunt_votes: 1500,
    hackernews_points: 1100,
    hackernews_mentions: 80,
    social_signals: { twitter_mentions: 20000, reddit_mentions: 10000, total_engagement: 30000 },
    search_interest: 80,
    trend_score: 85.3,
    trend_direction: 'rising',
    feature_innovation_score: 0.92,
    source: 'github',
    release_date: new Date('2022-10-01'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Jasper',
    slug: 'jasper',
    description: 'AI writing assistant for marketing teams. Generates content for blogs, social media, ads, emails, and more with brand voice consistency.',
    short_description: 'AI writing assistant for marketing content and brand-consistent copy.',
    website: 'https://jasper.ai',
    logo: '',
    category: 'AI Writing',
    sub_category: 'Content Generation',
    tags: ['ai', 'writing', 'marketing', 'content', 'copywriting', 'blog'],
    pricing: { model: 'Paid', starting_price: '$49/mo', currency: 'USD' },
    free_plan: false,
    features: ['Blog post generation', 'Ad copy creation', 'Social media content', 'Email templates', 'Brand voice', 'Content templates', 'Team collaboration'],
    github_stars: 0,
    producthunt_votes: 2500,
    hackernews_points: 300,
    social_signals: { twitter_mentions: 12000, reddit_mentions: 5000, total_engagement: 17000 },
    search_interest: 60,
    trend_score: 65.4,
    trend_direction: 'stable',
    feature_innovation_score: 0.72,
    source: 'producthunt',
    release_date: new Date('2021-01-15'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Runway',
    slug: 'runway',
    description: 'AI-powered creative suite for video generation, editing, and visual effects. Features Gen-2 for text-to-video and image-to-video generation.',
    short_description: 'AI video generation and editing platform with Gen-2 text-to-video.',
    website: 'https://runway.ml',
    logo: '',
    category: 'AI Video Generation',
    sub_category: 'Video Generation',
    tags: ['ai', 'video', 'video generation', 'text-to-video', 'creative', 'editing'],
    pricing: { model: 'Freemium', starting_price: '$12/mo', currency: 'USD' },
    free_plan: true,
    features: ['Text-to-video generation', 'Image-to-video', 'Video editing', 'Green screen', 'Motion tracking', 'Style transfer', 'Inpainting'],
    github_stars: 0,
    producthunt_votes: 1900,
    hackernews_points: 600,
    social_signals: { twitter_mentions: 18000, reddit_mentions: 8000, total_engagement: 26000 },
    search_interest: 70,
    trend_score: 76.1,
    trend_direction: 'rising',
    feature_innovation_score: 0.88,
    source: 'producthunt',
    release_date: new Date('2023-06-01'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Zapier AI',
    slug: 'zapier-ai',
    description: 'AI-powered automation platform that connects apps and automates workflows. Features AI actions for data processing, content generation, and intelligent routing.',
    short_description: 'AI-powered workflow automation connecting 6000+ apps.',
    website: 'https://zapier.com',
    logo: '',
    category: 'AI Automation',
    sub_category: 'Workflow Automation',
    tags: ['ai', 'automation', 'workflow', 'no-code', 'integration', 'productivity'],
    pricing: { model: 'Freemium', starting_price: '$19.99/mo', currency: 'USD' },
    free_plan: true,
    features: ['6000+ app integrations', 'AI-powered actions', 'Multi-step workflows', 'Conditional logic', 'Webhooks', 'Custom code steps', 'Team management'],
    github_stars: 0,
    producthunt_votes: 3200,
    hackernews_points: 500,
    social_signals: { twitter_mentions: 25000, reddit_mentions: 12000, total_engagement: 37000 },
    search_interest: 65,
    trend_score: 72.3,
    trend_direction: 'stable',
    feature_innovation_score: 0.78,
    source: 'producthunt',
    release_date: new Date('2023-09-01'),
    ai_relevance_score: 0.9,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'AI-powered search engine that provides direct, cited answers to questions using real-time web data and large language models.',
    short_description: 'AI search engine delivering cited answers from real-time web data.',
    website: 'https://perplexity.ai',
    logo: '',
    category: 'AI Research',
    sub_category: 'Knowledge Management',
    tags: ['ai', 'search', 'research', 'llm', 'knowledge', 'productivity'],
    pricing: { model: 'Freemium', starting_price: '$20/mo', currency: 'USD' },
    free_plan: true,
    features: ['AI-powered search', 'Real-time web data', 'Citations', 'Follow-up questions', 'Collections', 'Focus modes', 'API access'],
    github_stars: 0,
    producthunt_votes: 2100,
    hackernews_points: 900,
    social_signals: { twitter_mentions: 22000, reddit_mentions: 11000, total_engagement: 33000 },
    search_interest: 82,
    trend_score: 84.7,
    trend_direction: 'rising',
    feature_innovation_score: 0.90,
    source: 'hackernews',
    release_date: new Date('2022-12-01'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'AI writing and organization assistant integrated into Notion workspace. Helps with drafting, summarizing, brainstorming, and improving content directly in your documents.',
    short_description: 'AI assistant integrated into Notion for writing and organization.',
    website: 'https://notion.so/product/ai',
    logo: '',
    category: 'AI Productivity',
    sub_category: 'Note Taking',
    tags: ['ai', 'productivity', 'writing', 'notes', 'organization', 'collaboration'],
    pricing: { model: 'Paid', starting_price: '$10/mo', currency: 'USD' },
    free_plan: false,
    features: ['AI writing assistant', 'Content summarization', 'Translation', 'Brainstorming', 'Task extraction', 'Tone adjustment', 'Q&A on documents'],
    github_stars: 0,
    producthunt_votes: 2800,
    hackernews_points: 450,
    social_signals: { twitter_mentions: 18000, reddit_mentions: 9000, total_engagement: 27000 },
    search_interest: 68,
    trend_score: 70.9,
    trend_direction: 'stable',
    feature_innovation_score: 0.75,
    source: 'producthunt',
    release_date: new Date('2023-02-22'),
    ai_relevance_score: 0.95,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI voice synthesis platform offering realistic text-to-speech, voice cloning, and audio dubbing. Supports 29+ languages with natural-sounding voices.',
    short_description: 'AI voice synthesis with realistic text-to-speech and voice cloning.',
    website: 'https://elevenlabs.io',
    logo: '',
    category: 'AI Audio & Music',
    sub_category: 'Voice Synthesis',
    tags: ['ai', 'voice', 'text-to-speech', 'audio', 'voice cloning', 'multilingual'],
    pricing: { model: 'Freemium', starting_price: '$5/mo', currency: 'USD' },
    free_plan: true,
    features: ['Text-to-speech', 'Voice cloning', 'Audio dubbing', '29+ languages', 'Voice design', 'Projects', 'API access'],
    github_stars: 0,
    producthunt_votes: 1700,
    hackernews_points: 650,
    social_signals: { twitter_mentions: 15000, reddit_mentions: 7000, total_engagement: 22000 },
    search_interest: 73,
    trend_score: 74.6,
    trend_direction: 'rising',
    feature_innovation_score: 0.85,
    source: 'producthunt',
    release_date: new Date('2023-01-15'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Hugging Face',
    slug: 'hugging-face',
    description: 'The AI community platform for sharing models, datasets, and applications. Hosts 500k+ models, provides inference APIs, and offers Spaces for deploying AI apps.',
    short_description: 'AI community platform with 500K+ models, datasets, and deployment.',
    website: 'https://huggingface.co',
    logo: '',
    category: 'AI Research',
    sub_category: 'Knowledge Management',
    tags: ['ai', 'machine learning', 'open source', 'models', 'nlp', 'community', 'api'],
    pricing: { model: 'Freemium', starting_price: '$9/mo', currency: 'USD' },
    free_plan: true,
    features: ['Model hosting', 'Datasets hub', 'Inference API', 'Spaces (app deployment)', 'Transformers library', 'Community models', 'AutoTrain'],
    github_stars: 120000,
    github_forks: 24000,
    github_url: 'https://github.com/huggingface/transformers',
    github_star_growth: 150,
    producthunt_votes: 1200,
    hackernews_points: 1500,
    hackernews_mentions: 100,
    social_signals: { twitter_mentions: 35000, reddit_mentions: 15000, total_engagement: 50000 },
    search_interest: 88,
    trend_score: 91.2,
    trend_direction: 'rising',
    feature_innovation_score: 0.95,
    source: 'github',
    release_date: new Date('2018-10-01'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Canva AI',
    slug: 'canva-ai',
    description: 'AI-powered design platform with Magic Studio features including text-to-image, background removal, Magic Write content generator, and AI-powered design suggestions.',
    short_description: 'AI design platform with Magic Studio for image generation and editing.',
    website: 'https://canva.com',
    logo: '',
    category: 'AI Design',
    sub_category: 'Graphic Design',
    tags: ['ai', 'design', 'image generation', 'graphic design', 'marketing', 'productivity'],
    pricing: { model: 'Freemium', starting_price: '$12.99/mo', currency: 'USD' },
    free_plan: true,
    features: ['Magic Studio', 'Text-to-image', 'Background removal', 'Magic Write', 'Brand Kit', 'AI-powered design', 'Templates'],
    github_stars: 0,
    producthunt_votes: 3000,
    hackernews_points: 350,
    social_signals: { twitter_mentions: 20000, reddit_mentions: 10000, total_engagement: 30000 },
    search_interest: 75,
    trend_score: 73.8,
    trend_direction: 'stable',
    feature_innovation_score: 0.80,
    source: 'producthunt',
    release_date: new Date('2023-10-04'),
    ai_relevance_score: 0.95,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Suno',
    slug: 'suno',
    description: 'AI music generation platform that creates full songs with vocals, instruments, and lyrics from text prompts. Supports multiple genres and styles.',
    short_description: 'AI music generator creating full songs with vocals from text prompts.',
    website: 'https://suno.ai',
    logo: '',
    category: 'AI Audio & Music',
    sub_category: 'Music Generation',
    tags: ['ai', 'music', 'audio', 'text-to-music', 'creative', 'vocals'],
    pricing: { model: 'Freemium', starting_price: '$8/mo', currency: 'USD' },
    free_plan: true,
    features: ['Text-to-music', 'AI vocals', 'Multiple genres', 'Lyric generation', 'Song remixing', 'Download & share'],
    github_stars: 0,
    producthunt_votes: 1600,
    hackernews_points: 500,
    social_signals: { twitter_mentions: 12000, reddit_mentions: 6000, total_engagement: 18000 },
    search_interest: 70,
    trend_score: 71.5,
    trend_direction: 'rising',
    feature_innovation_score: 0.88,
    source: 'producthunt',
    release_date: new Date('2023-09-20'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Copy.ai',
    slug: 'copy-ai',
    description: 'AI-powered marketing copy generator for businesses. Creates social media posts, product descriptions, blog content, and email campaigns.',
    short_description: 'AI marketing copy generator for social media, blogs, and emails.',
    website: 'https://copy.ai',
    logo: '',
    category: 'AI Marketing',
    sub_category: 'Content Marketing',
    tags: ['ai', 'marketing', 'copywriting', 'social media', 'email', 'content'],
    pricing: { model: 'Freemium', starting_price: '$49/mo', currency: 'USD' },
    free_plan: true,
    features: ['Marketing copy generation', 'Social media posts', 'Blog content', 'Email campaigns', 'Product descriptions', 'Ad copy', 'Workflow automation'],
    github_stars: 0,
    producthunt_votes: 2100,
    hackernews_points: 200,
    social_signals: { twitter_mentions: 8000, reddit_mentions: 4000, total_engagement: 12000 },
    search_interest: 55,
    trend_score: 58.2,
    trend_direction: 'stable',
    feature_innovation_score: 0.65,
    source: 'producthunt',
    release_date: new Date('2020-10-01'),
    ai_relevance_score: 0.95,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Ollama',
    slug: 'ollama',
    description: 'Run large language models locally on your machine. Supports Llama, Mistral, Gemma, and many other open-source models with a simple command-line interface.',
    short_description: 'Run LLMs locally - supports Llama, Mistral, Gemma and more.',
    website: 'https://ollama.com',
    logo: '',
    category: 'AI Coding',
    sub_category: 'Code Generation',
    tags: ['ai', 'llm', 'open source', 'local', 'developer', 'privacy', 'self-hosted'],
    pricing: { model: 'Open Source', currency: 'USD' },
    free_plan: true,
    features: ['Local LLM inference', 'Model library', 'CLI interface', 'API server', 'Custom models', 'GPU acceleration', 'Modelfile creation'],
    github_stars: 75000,
    github_forks: 5500,
    github_url: 'https://github.com/ollama/ollama',
    github_star_growth: 300,
    producthunt_votes: 1300,
    hackernews_points: 1200,
    hackernews_mentions: 90,
    social_signals: { twitter_mentions: 20000, reddit_mentions: 12000, total_engagement: 32000 },
    search_interest: 85,
    trend_score: 87.9,
    trend_direction: 'rising',
    feature_innovation_score: 0.92,
    source: 'github',
    release_date: new Date('2023-07-18'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'v0 by Vercel',
    slug: 'v0-by-vercel',
    description: 'AI-powered UI generation tool by Vercel. Creates React components and full web interfaces from text descriptions using shadcn/ui and Tailwind CSS.',
    short_description: 'AI UI generator creating React components from text descriptions.',
    website: 'https://v0.dev',
    logo: '',
    category: 'AI Coding',
    sub_category: 'Code Generation',
    tags: ['ai', 'coding', 'ui', 'react', 'web development', 'design', 'developer'],
    pricing: { model: 'Freemium', starting_price: '$20/mo', currency: 'USD' },
    free_plan: true,
    features: ['Text-to-UI', 'React component generation', 'Tailwind CSS', 'shadcn/ui components', 'Code export', 'Iterative refinement'],
    github_stars: 0,
    producthunt_votes: 1800,
    hackernews_points: 700,
    social_signals: { twitter_mentions: 15000, reddit_mentions: 7000, total_engagement: 22000 },
    search_interest: 75,
    trend_score: 78.4,
    trend_direction: 'rising',
    feature_innovation_score: 0.90,
    source: 'hackernews',
    release_date: new Date('2023-10-25'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'AI-powered video and audio editing platform. Edit media by editing text transcripts, with features like filler word removal, eye contact correction, and AI voice cloning.',
    short_description: 'AI video/audio editor - edit media by editing text transcripts.',
    website: 'https://descript.com',
    logo: '',
    category: 'AI Video Generation',
    sub_category: 'Video Editing',
    tags: ['ai', 'video', 'audio', 'editing', 'transcription', 'podcast', 'creative'],
    pricing: { model: 'Freemium', starting_price: '$24/mo', currency: 'USD' },
    free_plan: true,
    features: ['Text-based video editing', 'AI transcription', 'Filler word removal', 'Eye contact correction', 'Voice cloning', 'Screen recording', 'Green screen'],
    github_stars: 0,
    producthunt_votes: 2400,
    hackernews_points: 400,
    social_signals: { twitter_mentions: 10000, reddit_mentions: 5000, total_engagement: 15000 },
    search_interest: 60,
    trend_score: 64.3,
    trend_direction: 'stable',
    feature_innovation_score: 0.82,
    source: 'producthunt',
    release_date: new Date('2019-10-01'),
    ai_relevance_score: 0.95,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'Anthropic Claude',
    slug: 'anthropic-claude',
    description: 'Advanced AI assistant by Anthropic with strong reasoning, coding, and analysis capabilities. Known for being helpful, harmless, and honest with long context window support.',
    short_description: 'Advanced AI assistant with strong reasoning and 200K context window.',
    website: 'https://claude.ai',
    logo: '',
    category: 'AI Chatbots',
    sub_category: 'Virtual Assistant',
    tags: ['ai', 'chatbot', 'llm', 'anthropic', 'coding', 'research', 'productivity'],
    pricing: { model: 'Freemium', starting_price: '$20/mo', currency: 'USD' },
    free_plan: true,
    features: ['Advanced reasoning', '200K context window', 'Code generation', 'Document analysis', 'Artifacts', 'Projects', 'API access'],
    github_stars: 0,
    producthunt_votes: 1500,
    hackernews_points: 1800,
    hackernews_mentions: 120,
    social_signals: { twitter_mentions: 25000, reddit_mentions: 15000, total_engagement: 40000 },
    search_interest: 80,
    trend_score: 86.1,
    trend_direction: 'rising',
    feature_innovation_score: 0.93,
    source: 'hackernews',
    release_date: new Date('2023-03-14'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'AI pair programming tool that provides code suggestions, completions, and generation directly in your IDE. Supports VS Code, JetBrains, Neovim, and more.',
    short_description: 'AI pair programmer with real-time code suggestions in your IDE.',
    website: 'https://github.com/features/copilot',
    logo: '',
    category: 'AI Coding',
    sub_category: 'Code Generation',
    tags: ['ai', 'coding', 'github', 'code completion', 'developer', 'ide', 'productivity'],
    pricing: { model: 'Paid', starting_price: '$10/mo', currency: 'USD' },
    free_plan: false,
    features: ['Code completion', 'Chat in IDE', 'Code generation', 'Multi-language support', 'Context-aware suggestions', 'CLI integration', 'Pull request summaries'],
    github_stars: 0,
    producthunt_votes: 3100,
    hackernews_points: 1400,
    hackernews_mentions: 100,
    social_signals: { twitter_mentions: 30000, reddit_mentions: 15000, total_engagement: 45000 },
    search_interest: 82,
    trend_score: 83.7,
    trend_direction: 'stable',
    feature_innovation_score: 0.88,
    source: 'manual',
    release_date: new Date('2022-06-21'),
    ai_relevance_score: 1.0,
    is_active: true,
    is_verified: true,
    needs_review: false,
  },
];

async function seed() {
  try {
    logger.info('🌱 Starting database seed...');
    await database.connect();

    // Clear existing data
    const count = await AiTool.countDocuments();
    if (count > 0) {
      logger.info(`  Existing tools: ${count}. Clearing...`);
      await AiTool.deleteMany({});
    }

    // Insert sample tools
    const inserted = await AiTool.insertMany(sampleTools);
    logger.info(`✅ Seeded ${inserted.length} AI tools`);

    // Display categories
    const cats = await AiTool.getCategoryStats();
    logger.info('📊 Category distribution:');
    for (const cat of cats) {
      logger.info(`   ${cat._id}: ${cat.count} tools (avg score: ${cat.avg_trend_score?.toFixed(1)})`);
    }

    await database.disconnect();
    logger.info('🌱 Seed complete!');
    process.exit(0);
  } catch (error) {
    logger.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
